services:
  mysql:
    image: mariadb:11.4
    container_name: featherpanel_mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-featherpanel_root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-featherpanel}
      MARIADB_USER: ${MARIADB_USER:-featherpanel}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-featherpanel_password}
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - featherpanel_network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-pfeatherpanel_root"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: featherpanel_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-featherpanel_redis}
    volumes:
      - redis_data:/data
    networks:
      - featherpanel_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  backend:
    image: ghcr.io/mythicalltd/featherpanel-backend:latest
    container_name: featherpanel_backend
    restart: unless-stopped
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=${MARIADB_DATABASE:-featherpanel}
      - DATABASE_USER=${MARIADB_USER:-featherpanel}
      - DATABASE_PASSWORD=${MARIADB_PASSWORD:-featherpanel_password}
      - DATABASE_ENCRYPTION=xchacha20
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-featherpanel_redis}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - featherpanel_attachments:/var/www/html/storage/attachments
      - featherpanel_addons:/var/www/html/storage/addons
      - featherpanel_logs:/var/www/html/storage/logs
      - featherpanel_config:/var/www/html/storage/config
    networks:
      - featherpanel_network

  frontend:
    image: ghcr.io/mythicalltd/featherpanel-frontend:main
    container_name: featherpanel_frontend
    restart: unless-stopped
    ports:
      - "4831:80"
    depends_on:
      - backend
    networks:
      - featherpanel_network

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  featherpanel_attachments:
    driver: local
  featherpanel_addons:
    driver: local
  featherpanel_logs:
    driver: local
  featherpanel_config:
    driver: local

networks:
  featherpanel_network:
    driver: bridge
