
services:
  mysql:
    image: mariadb:11.4
    container_name: featherpanel_mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-featherpanel_root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-featherpanel}
      MARIADB_USER: ${MARIADB_USER:-featherpanel}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-featherpanel_password}
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - featherpanel_network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-pfeatherpanel_root"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: featherpanel_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-featherpanel_redis}
    volumes:
      - redis_data:/data
    networks:
      - featherpanel_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: featherpanel_backend
    restart: unless-stopped
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=${MARIADB_DATABASE:-featherpanel}
      - DATABASE_USER=${MARIADB_USER:-featherpanel}
      - DATABASE_PASSWORD=${MARIADB_PASSWORD:-featherpanel_password}
      - DATABASE_ENCRYPTION=plaintext
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-featherpanel_redis}
    # Mount the entire backend directory to the container's working directory for live development
    volumes:
      - ./backend:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - featherpanel_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: featherpanel_frontend
    restart: unless-stopped
    ports:
      - "4831:80"
    # Mount the entire frontend directory to the container's working directory for live development
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - featherpanel_network

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local

networks:
  featherpanel_network:
    driver: bridge
