CREATE TABLE `featherpanel_ldap_providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `host` VARCHAR(255) NOT NULL,
  `port` INT NOT NULL DEFAULT 389,
  `use_tls` ENUM('true','false') NOT NULL DEFAULT 'false',
  `use_ssl` ENUM('true','false') NOT NULL DEFAULT 'false',
  `bind_dn` VARCHAR(255) DEFAULT NULL,
  `bind_password` TEXT DEFAULT NULL,
  `base_dn` VARCHAR(255) NOT NULL,
  `user_filter` VARCHAR(255) NOT NULL DEFAULT '(uid={username})',
  `username_attribute` VARCHAR(255) NOT NULL DEFAULT 'uid',
  `email_attribute` VARCHAR(255) NOT NULL DEFAULT 'mail',
  `first_name_attribute` VARCHAR(255) DEFAULT 'givenName',
  `last_name_attribute` VARCHAR(255) DEFAULT 'sn',
  `group_filter` VARCHAR(255) DEFAULT NULL,
  `group_attribute` VARCHAR(255) DEFAULT 'memberOf',
  `required_group` VARCHAR(255) DEFAULT NULL,
  `auto_provision` ENUM('true','false') NOT NULL DEFAULT 'false',
  `sync_attributes` ENUM('true','false') NOT NULL DEFAULT 'false',
  `enabled` ENUM('true','false') NOT NULL DEFAULT 'true',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `featherpanel_ldap_providers_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
