CREATE TABLE IF NOT EXISTS `featherpanel_webspaces` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`uuid` CHAR(36) NOT NULL,
	`name` VARCHAR(191) NOT NULL,
	`description` TEXT DEFAULT NULL,
	`web_node_id` INT(11) NOT NULL,
	`webplate_id` INT(11) NOT NULL,
	`disk` INT(10) UNSIGNED NOT NULL DEFAULT 1024,
	`domains` JSON DEFAULT NULL,
	`ssl` TINYINT(1) NOT NULL DEFAULT 0,
	`backend_port` INT(10) UNSIGNED NOT NULL DEFAULT 0,
	`document_root` VARCHAR(191) NOT NULL DEFAULT 'public',
	`image` VARCHAR(191) DEFAULT NULL,
	`status` VARCHAR(32) NOT NULL DEFAULT 'installing',
	`state` VARCHAR(32) NOT NULL DEFAULT 'stopped',
	`owner_id` INT(11) DEFAULT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE KEY `featherpanel_webspaces_uuid_unique` (`uuid`),
	KEY `featherpanel_webspaces_web_node_id` (`web_node_id`),
	KEY `featherpanel_webspaces_webplate_id` (`webplate_id`),
	CONSTRAINT `featherpanel_webspaces_web_node_id_foreign` FOREIGN KEY (`web_node_id`) REFERENCES `featherpanel_web_nodes` (`id`) ON DELETE CASCADE,
	CONSTRAINT `featherpanel_webspaces_webplate_id_foreign` FOREIGN KEY (`webplate_id`) REFERENCES `featherpanel_webplates` (`id`) ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;
