name: Bug Report
description: Something isn't working quite right in the software.
labels: [not confirmed]
body:
- type: markdown
  attributes:
    value: |
      Bug reports should only be used for reporting issues with how the software works. For assistance installing this software, as well as debugging issues with dependencies, please use our [Discord server](https://discord.mythical.systems).

- type: textarea      
  attributes:
    label: Current Behavior
    description: Please provide a clear & concise description of the issue.
  validations:
    required: true

- type: textarea      
  attributes:
    label: Expected Behavior
    description: Please describe what you expected to happen.
  validations:
    required: true

- type: textarea      
  attributes:
    label: Steps to Reproduce
    description: Please be as detailed as possible when providing steps to reproduce, failure to provide steps will result in this issue being closed.
  validations:
    required: true

- type: input
  id: featherpanel-version
  attributes:
    label: Framework Version
    description: Version number of your FeatherPanel (latest is not a version)
    placeholder: 1.0.0
  validations:
    required: true

- type: textarea
  id: panel-logs
  attributes:
    label: Error Logs
    description: |
      Run the following command to collect logs on your system.
      Panel: `docker exec featherpanel_backend php cli logs`
    placeholder: "https://api.mythical.systems/logs/123456&plain"
    render: bash
  validations:
    required: false
    
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please [search here](https://github.com/mythicalltd/featherpanel/issues) to see if an issue already exists for your problem.
    options:
    - label: I have searched the existing issues before opening this issue.
      required: true
    - label: I have provided all relevant details.
      required: true
    - label: I have checked in the Discord server and believe this is a bug with the FeatherPanel, and not a configuration issue with my specific system.
      required: true