name: Frontend Jobs

on: [push, pull_request]
jobs:
  build:
    name: Frontend Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node-version: [24]
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            echo "pnpm-lock.yaml file not found"
            exit 1
          fi
      - name: Build
        run: pnpm build
  lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node-version: [24]
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            echo "pnpm-lock.yaml file not found"
            exit 1
          fi
      - name: Lint
        run: pnpm lint
  format:
    name: Frontend Format
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node-version: [24]
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            echo "pnpm-lock.yaml file not found"
            exit 1
          fi
      - name: Format
        run: pnpm format
